server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  # 默认失效剔除时间（毫秒）
  server:
    eviction-interval-timer-in-ms: 60000
